version: '{build}'
skip_tags: true
image: Visual Studio 2017
configuration: Release
build_script:
- ps: ./Build.ps1
test: off
artifacts:
- path: artifacts/Seq.Extensions.Logging.*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: owIruqEXZlFwqcSBYyjR19/8EodS+aXFzZmBwqlaYnDE/uy1X+KsuI5QH3p9iBmx
  skip_symbols: true
  on:
    branch: /^(master|dev)$/
