version: '{build}'
skip_tags: true
image: Visual Studio 2019
build_script:
- ps: ./Build.ps1
test: off
artifacts:
- path: artifacts/Seq.Extensions.Logging.*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: 94298ksNMfJ2LkBV3Lw9o4JVzKvVPPMHF91p0XjsBhNWVeMX2NeROX4fpio6BsQy
  skip_symbols: true
  on:
    branch: /^(master|dev)$/
